version: "3.9"
services:
  mongo_serv:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  nats:
    image: nats:latest
    restart: always
    expose:
      - "4222"
    ports:
      - "8222:8222"
  gateway:
    build: ./client
    ports:
      - 3001:3001
    environment:
      MONGODB_URI: ${MONGODB_URI}
      # NATS_URL: nats://nats:4222
      NATS_URL: ${NATS_URL}
    depends_on:
      - mongo_serv
  bookstore_api:
    build: ./bookstore
    # environment:
      # MONGODB_URI: ${MONGODB_URI}
      # NATS_URL: nats://nats:4222
      # NATS_URL: ${NATS_URL}
    depends_on:
      - mongo_serv
      - gateway
  user_api:
    build: ./user
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NATS_URL: ${NATS_URL}
    depends_on:
      - mongo_serv
      - gateway
volumes:
  mongo_db: {}
